# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Kalmyk spellchecker"
xal = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Kalmyk, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
xal = "TRANSLATE: A spellchecker for Kalmyk, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.xal"

[windows]
system_product_code = "{C15872FF-C2A9-444A-8A43-E51D7774B569}_is1"
legacy_product_codes = [
    { value = "D4D590FB-87AD-4C76-8EEE-A8AF71134D8A", kind = "nsis" },
    { value = "CC014535-47B6-4CF9-BF04-582EE17D641A", kind = "nsis" }
]

[package.speller]
name = "Kalmyk"
version = "0.1.1"

[package.grammar]
name = "Kalmyk"
version = "0.1.0"

[package.tts-text-proc]
name = "Kalmyk"
version = "0.1.0"
