template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "kalm1243"
__REPO__ = "lang-xal"
__UND2C__ = "xal"
__UNDEFINED__ = "Kalmyk"
__UND__ = "xal"
