template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "kalm1243"
__REPO__ = "lang-xal"
__UND2C__ = "xal"
__UNDEFINED__ = "Kalmyk"
__UND__ = "xal"
